[package]
name = "unify-imperial"
version = "0.0.2"
entrypoint = "lib.typ"
authors = ["Christopher Hecker", "schmic41"]
repository = "https://github.com/schmic41/unify-imperial"
license = "MIT"
description = "A fork of checker's unify package that replaces metric units with imperial units."
exclude = ["examples"]
